### ISSUE TITLE
Auth Ready For Review

### ISSUE THREAD

**Issue by aberenjian89** [aberenjian89/pexcel#1]

**Comment by s-pangburn** [comment]
Great work Ali! Just a few tweaks, mostly with styling, and one bugfix and I'll mark this feature as complete!

- [x] The size of the fonts in the navbar should not change between the white version and the dark version on the splash page
- [x] https://pexcel-aa.herokuapp.com/#/sdlkfjslkdfjlksjflsj <-- This should redirect to either your splash page or the login form.
- [x] Unless you plan to have something else on the bottom of the splash page eventually, you should make sure your background photo fills the screen (CSS `height: 100%;`)
- [x] When you log in, the user icon that creates the dropdown menu should do `cursor: pointer` on hover.
   - [x] On that note, don't include icons that won't do anything (I'm thinking in particular about the notifications icon)
- [x] Ideally the entire `li` for each item in the dropdown would darken the color on hover and `cursor:pointer`, not just the text.
- [x] Don't include "Forgot Password?" unless you plan to implement a mailer
- [x] "Log In to PEXCEL" and "Join PEXCEL" should be bold or bigger in some way to keep things visually organized.
- [x] There should be a little more padding on the left and right of your `input` elements.

**Comment by aberenjian89** [comment]
Can you please review again ?

Thanks :)

**Comment by s-pangburn** [comment]
All good! 👌
