### ISSUE TITLE
Please Review

### ISSUE THREAD

**Issue by aberenjian89** [aberenjian89/pexcel#7]

**Comment by s-pangburn** [comment]
I strongly recommend using inline code (three backticks ```) instead of a screenshot for code snippets. It will be easier for technical recruiters to read.

```
like this
```

**Comment by s-pangburn** [comment]
Also instead of saying "Upload process is done by this" and showing the code, spend some time explaining the code. Recruiters will be interested in your ability to explain technical concepts, especially code you've written yourself.

**Comment by s-pangburn** [comment]
Good work Ali! 👍
